apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits" 
spec:
  limits:
    -
      type: "Container"
      max:
        cpu: "300m" 
        memory: "512Mi" 
      min:
        cpu: "50m" 
        memory: "256Mi" 
